name: Push to Main

on:
  push:
    branches:
      - your-branch-name   # Replace 'your-branch-name' with the name of your source branch

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: Commit and push changes
      run: |
        git checkout main
        git merge --ff-only ${{ github.ref }}
        git push origin main
